### ISSUE TITLE
`granted console` fails with code 400

### ISSUE THREAD

**Issue by chrnorm** [common-fate/granted#655] opened 2024-05-09 15:59 UTC
Not sure exactly which release has introduced this but we have had a few reports of this issue:

```
❯ granted console
[✘] opening console failed with code 400
```

**Comment by shwethaumashanker** [comment] 2024-05-09 16:17
Temporary workaround: Add `DefaultExportAllEnvVar=true` to your `~/.granted/config` file. This config setting will export all environment variables by default when the `credential_process` is used; we suspect that this is the root cause of the error.
We are working on a permanent fix for this!

**Comment by dpendolino-ibotta** [comment] 2024-05-22 18:08
@chrnorm I just started getting this error too and your workaround doesn't seem to have any effect for me. Was there anything else that was needed?

**Comment by shwethaumashanker** [comment] 2024-05-22 18:26
@dpendolino-ibotta We’ve just released a fix for this in Granted [v0.27.0](https://github.com/common-fate/granted/releases/tag/v0.27.0)! Can you please try upgrading to `v0.27.0` and let us know if you are still seeing this issue

**Comment by dpendolino-ibotta** [comment] 2024-05-22 18:36
@shwethaumashanker that did the trick, thanks!

**Comment by shwethaumashanker** [comment] 2024-05-22 19:10
Fixed in Granted [v0.27.0](https://github.com/common-fate/granted/releases/tag/v0.27.0)!

**Closed by shwethaumashanker** 2024-05-22 19:10 UTC
