### ISSUE TITLE
Config file perrmisions appear to be wrong

### ISSUE THREAD

**Issue by jpbelleau** [common-fate/granted#754] opened 2024-09-24 16:16 UTC
It appears the file permissions for the Granted config directory, when created, are wrong.  We saw the change in behavior with the 0.34 release.  If fails when running `granted registry add ...`.  Looking at #751, the wrong permissions were used for directory creation.

**Comment by chrnorm** [comment] 2024-09-24 16:29
Thanks for flagging this @jpbelleau, I'm working on a fix for this now

**Comment by jpbelleau** [comment] 2024-09-24 16:39
I almost have I have one done and working to open a PR.

**Comment by chrnorm** [comment] 2024-09-24 16:41
Thankyou. My proposed change is to simply revert #751

**Comment by jpbelleau** [comment] 2024-09-24 16:42
I have not sent a change to granted yet and have some setup to do.  I found the 2 offending issues and no revert should be needed.

**Comment by jpbelleau** [comment] 2024-09-24 16:52
Added PR for the config folder fixes

**Comment by chrnorm** [comment] 2024-09-24 17:16
@jpbelleau this is now released in [v0.34.1](https://github.com/common-fate/granted/releases/tag/v0.34.1), thanks again for the report. The release binaries are now building and will be live in the next 10 minutes or so. I ended up merging my PR over yours because I wanted to shift the permissions back to `0600`. I marked you as a coauthor on the PR though to highlight your contribution - thankyou so much for your help here.

Some context too on why #751 was implemented at all - @JoshuaWilkes noticed recently that that the `~/.granted/config` file was executable on his machine, and the PR was put up as a response to this. Upon reviewing the change though I think that the Josh's `~/.granted/config` file may have been made executable outside of Granted, as I was unable to reproduce this myself.

**Closed by chrnorm** 2024-09-24 17:16 UTC
