### ISSUE TITLE
Cannot open a browser session for profile because it does not assume a role

### ISSUE THREAD

**Issue by avishayil** [common-fate/granted#48] opened 2022-02-24 10:29 UTC
Hi, Thanks for this initiative, nice work.

I'm using Okta with AWS federation and `saml2aws` CLI tool in order to get temporary credentials for AWS CLI.
After setting up the profile with `granted` and trying to use the browser session functionality, I'm getting the following error message

````
Attempting to open using active role...

Cannot open a browser session for profile: xxxx because it does not assume a role
````

I have credentials and aws profile configured correctly, and when running `aws sts get-caller-identity` I'm getting my identity correctly:
````
{
    "UserId": "AROXXXXXXXXXXXXX:xxx@xxx.xxx.xxx",
    "Account": "123456789123",
    "Arn": "arn:aws:sts::xxxxxxxxxxxx:assumed-role/Admin/xxx@xxx.xxx.xxx"
}
````

Output from running `assume`:
````
§ assume
? Please select the profile you would like to assume: xxxxxx
[xxxxxx](us-east-1) session credentials ready
````

**Comment by chrnorm** [comment] 2022-02-24 10:34
Thanks for the issue @avishayil! To help us replicate the issue, is it possible to share a redacted version of your `~/.aws/config` file? (excluding any account IDs or SSO start URLs).

I think the problem here is due to Granted not supporting the SAML2.0 web federation login flow that you’re using with Okta, but taking a quick look at your config will help confirm.

**Comment by avishayil** [comment] 2022-02-24 10:48
Thanks @chrnorm , my `~/.aws/config` file is just a list of profiles with configured regions:
````
[default]
region=us-east-1

[profile xxxx]
region=eu-west-1

[profile yyyy]
region=eu-west-1

[profile zzzz]
region=eu-west-1

**Comment by adedommelin-ducksify** [comment] 2022-02-25 09:19
Hello @chrnorm,

Thanks for the good work !

I can confirm the same issue as @avishayil, not using Okta (simple IAM users), running on MacOS, granted v0.1.5, with Chrome as a default browser.

**Comment by meyerjrr** [comment] 2022-03-02 23:44
Hey @avishayil and @adedommelin-ducksify! We just rolled out Granted v0.1.7 which included support for different SSO credential proxy's. Would you be able to test whether you are still running into issue's using Granted with your configurations?

**Comment by avishayil** [comment] 2022-03-03 12:13
Thanks @meyerjrr I'm now having the following issue:
````
? Please select the profile you would like to assume: *******
operation error STS: GetFederationToken, https response error StatusCode: 403, RequestID: 81ac02d7-fa67-4b50-8af2-9d9c0c80a675, api error AccessDenied: Cannot call GetFederationToken with session credentials
````

Because i'm already using AssumeRoleWithSAML in my workflow. Is there any possibility to use the current credentials instead of requesting new credentials using `GetFederationToken`?

**Comment by meyerjrr** [comment] 2022-03-03 23:47
Closing this issue and will be tracking it under #89

**Closed by meyerjrr** 2022-03-03 23:47 UTC
