### ISSUE TITLE
IAM + MFA does not work after adding credentials to the granted keyring

### ISSUE THREAD

**Issue by subpardaemon** [common-fate/granted#543] opened 2023-11-06 16:03 UTC
Hi, i can confirm that this is an issue still present in 0.20.0.

We use classic IAM + role assumption. If we keep the credentials in its plaintext form, ie. not using the `credential_process = granted credential-process --profile=base` line granted adds after an import, then MFA works splendidly. Once we add the credentials to the keyring and this line appears in `~/.aws/config` it no longer asks for the MFA even if the session expires. Tried `granted cache clear` with removing just the current session, this does not help. Removing the cached credentials removes the whole keyring, therefore leaving Granted in an inoperable state (empty `~/.aws/credentials` file).

It looks like the `credential-process` module does not have a concept of needing to ask for an MFA if Granted is not being used with SSO.

`~/.aws/credentials` before encoding (when MFA prompt works):
```
[base]
aws_access_key_id=<AWS access key from AWS setup>
aws_secret_access_key=<AWS access key secret from AWS setup>
```

`~/.aws/config` before encoding:
```
[profile base]
region             = us-east-1
mfa_serial         = arn:aws:iam::<whatever>
```

After `granted credentials import base`:
`~/.aws/credentials` is empty

`~/.aws/config` before encoding:
```
[profile base]
region             = us-east-1
mfa_serial         = arn:aws:iam::<whatever>
credential_process = granted credential-process --profile=base
```

**Comment by subpardaemon** [comment] 2023-11-06 16:30
See https://github.com/common-fate/granted/issues/405#issuecomment-1748718937 -- that issue is closed but the issue itself is still present. My biggest concern is that we cannot use granted without MFA, but we cannot use granted safely with the cleartext secrets.

**Comment by subpardaemon** [comment] 2023-11-06 16:46
There is a very convoluted workaround, tho, once the credentials are encrypted:
```
assume base --export
# comment out credential_process line in ~/.aws/config
granted cache clear
# choose session and base
assume base
# will ask for MFA
# empty out ~/.aws/credentials
```
But to do this every day... 🤣

**Comment by shwethaumashanker** [comment] 2023-11-07 21:23
Thank you so much for reporting the issue and providing the additional context, @subpardaemon. I'm working on replicating and debugging the issue. I'll keep you informed once I have any updates 😁

**Comment by subpardaemon** [comment] 2023-11-08 16:45
@shwethaumashanker let me know if i can help. If there is a debug mode in the app, generating logs, i'm more than happy to use it and send you the results. I can also debug the environment variables, etc.

**Comment by mfzl** [comment] 2023-11-09 07:09
Just to add some context this was fixed with #429  because I had a similar issue, it could even be the same issue

The MFA work done on that PR is now refactored and merged with #474, which reintroduced the issue for me.

The issue is that: 

https://github.com/common-fate/granted/blob/fcb95bbd07261d2cbaf46738b186a19623378fe3/pkg/cfaws/assumer_aws_iam.go#L25-L28

Assumes that if credentials are stored in secure storage it's good to go, but it should still consider the case of MFA in that block and ask for it. Which is what #429 did

**Comment by subpardaemon** [comment] 2023-11-20 10:03
any progress regarding this? my team has a commitment to migrate to granted, and this is a blocking issue. let me know if i can help with this.

**Comment by shwethaumashanker** [comment] 2023-11-20 21:56
Hi @subpardaemon, I apologize for the delay. Thank you for using Granted and recommending it to your team. I am able to replicate the error. I've encountered some unexpected hurdles during debugging, but I'm working on resolving it

**Comment by shwethaumashanker** [comment] 2023-11-27 20:46
@subpardaemon @mfzl, [v0.20.3](https://github.com/common-fate/granted/releases/tag/v0.20.3) includes the fix for this issue. Please let us know if it works for you!

**Comment by subpardaemon** [comment] 2023-11-28 08:23
> @subpardaemon @mfzl, [v0.20.3](https://github.com/common-fate/granted/releases/tag/v0.20.3) includes the fix for this issue. Please let us know if it works for you!

do you know when 0.20.3 is expected to hit brew? i did an upgrade this morning but it only got me to 0.20.2 from 0.20.0.

**Comment by subpardaemon** [comment] 2023-11-28 08:42
my bad for not executing `brew update` before `brew upgrade`. 😄 will test 0.20.3 tomorrow as i already have a valid token for today.

**Comment by mfzl** [comment] 2023-11-29 19:52
Hey @shwethaumashanker 👋🏾 

It is working for me. Thanks so much.

**Closed** 2023-11-29 20:40 UTC

**Comment by subpardaemon** [comment] 2023-11-30 10:22
I can also confirm it's working. Thank you @shwethaumashanker for the speedy fix!
