### ISSUE TITLE
[Docs/Install] APT install fails with "File has unexpected size (1488 != 1412). Mirror sync in progress?"

### ISSUE THREAD

**Issue by jgreenbow** [common-fate/granted#778] opened 2024-10-10 19:19 UTC
Following https://docs.commonfate.io/granted/getting-started#installing-the-cli, the key is successfully installed, fingerprint verified, and apt list added.

Running `sudo apt update` results in

```bash
> sudo apt update

...  (snipped)

Get:24 https://apt.releases.commonfate.io stable/main amd64 Packages [1,412 B]                     
Err:24 https://apt.releases.commonfate.io stable/main amd64 Packages                    
  File has unexpected size (1488 != 1412). Mirror sync in progress? [IP: 18.238.217.24 443]
  Hashes of expected file:
   - Filesize:1412 [weak]
   - SHA256:758a8d554a5630dd2f890146b57d3fb9eda02dd08229b31fb6594a5cca0fb6cc
   - SHA1:9ccfdd57482a6be010a8b8d4eb7b38fca364b368 [weak]
   - MD5Sum:a95185e90cbae66eeb729301a5dda9d9 [weak]
  Release file created at: Fri, 04 Oct 2024 11:38:17 +0000

... (snipped)       

Fetched 4,988 kB in 3s (1,977 kB/s)                        
Reading package lists... Done
E: Failed to fetch https://apt.releases.commonfate.io/dists/stable/main/binary-amd64/Packages.gz  File has unexpected size (1488 != 1412). Mirror sync in progress? [IP: 18.238.217.24 443]
   Hashes of expected file:
    - Filesize:1412 [weak]
    - SHA256:758a8d554a5630dd2f890146b57d3fb9eda02dd08229b31fb6594a5cca0fb6cc
    - SHA1:9ccfdd57482a6be010a8b8d4eb7b38fca364b368 [weak]
    - MD5Sum:a95185e90cbae66eeb729301a5dda9d9 [weak]
   Release file created at: Fri, 04 Oct 2024 11:38:17 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

I assume an InRelease file needs to be updated with the appropriate hash/filesize.

**Comment by jgreenbow** [comment] 2024-10-10 19:20
Current InRelease file (https://apt.releases.commonfate.io/dists/stable/InRelease)

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Origin: Common Fate APT Repository
Label: Common Fate
Suite: stable
Codename: stable
Version: 1.0
Architectures: amd64 arm64 i386
Components: main
Description: 
Date: Fri, 04 Oct 2024 11:38:17 UTC
MD5Sum:
 30bcdcf225f7dcb7feb8d224b8f5aeb4 6300 main/binary-amd64/Packages
 a95185e90cbae66eeb729301a5dda9d9 1412 main/binary-amd64/Packages.gz
 3dfd54c8ca1a38f705de35af53892ca1 6300 main/binary-arm64/Packages
 9373f516b827dd327d75719de3df17c1 1400 main/binary-arm64/Packages.gz
 bd1b79f174aec5b2ee0096500adb0b07 6244 main/binary-i386/Packages
 1fab0e5109bdcf10baeba3fb83cf9862 1409 main/binary-i386/Packages.gz
SHA1:
 663b4fe2464c08a45ba3a3cf635cb61afcbb742b 6300 main/binary-amd64/Packages
 9ccfdd57482a6be010a8b8d4eb7b38fca364b368 1412 main/binary-amd64/Packages.gz
 7e44f210ed7505fe8c739ba986846f91a01cf288 6300 main/binary-arm64/Packages
 2ef453b859f924526fc41d13365d117821cc6354 1400 main/binary-arm64/Packages.gz
 baeb5c900f529f09a2fbf26056fe3a0f6c3b7366 6244 main/binary-i386/Packages
 ac36978c1d98915694978b7cd8444cd498076c25 1409 main/binary-i386/Packages.gz
SHA256:
 5f4b4c088b592ee8c546e1eeb03b485ac924ad2f0fece053b9e74f027269f05f 6300 main/binary-amd64/Packages
 758a8d554a5630dd2f890146b57d3fb9eda02dd08229b31fb6594a5cca0fb6cc 1412 main/binary-amd64/Packages.gz
 d6c8151d00b7533f6e266b4c61e28c12e88efd2a99d33a3c511072f8b50ee38f 6300 main/binary-arm64/Packages
 525d73ec4cdc3e2a6c8dc86085ca29c740e96de799f2bc2b0a297d2e12006838 1400 main/binary-arm64/Packages.gz
 28f22b9555cb5572f8bc72c410a98283002b9e8d486efc3ce139af7ed588d1e7 6244 main/binary-i386/Packages
 d6528d3a1698da2c9b122435ab0a6420775e4dd375bf447e079ae874e95ab50b 1409 main/binary-i386/Packages.gz
-----BEGIN PGP SIGNATURE-----

iHUEARYKAB0WIQR4Ok0aMFdNKr7QSd3enWMdLR3JRAUCZv/TswAKCRDenWMdLR3J
RD9CAQCTDiY9iSMuNeSDoNjy5b1SFQ0rmNqqbUKQu4T79DeMbgD/UWhLumfVaX1a
mBxNZdAKKFQ0SAqETVZmMHzCWninNgE=
=CESf
-----END PGP SIGNATURE-----
```

**Comment by chrnorm** [comment] 2024-10-10 20:54
The APT repository uses AWS CloudFront as a caching layer - I suspect what has happened here is that the cache wasn't correctly invalidated and you've received an old `InRelease` file. I recently automated the APT release process but it looks like the release process does not invalidate the cache.

I've just triggered an invalidation now, @jgreenbow could you please retry `sudo apt update` and let me know if this is fixed for you? I've tested myself on an Ubuntu box and it seems fixed for me.

**Comment by jgreenbow** [comment] 2024-10-11 15:00
No luck 😢

I ran the following
- `sudo apt update`
- `sudo apt clean && sudo apt update`
- `sudo apt clean && sudo apt update` on VPN to another country (CA to UK)
  - and CA to US

All returned the original error (concerning main/binary-amd64/Packages.gz).

Inspecting the link directly confirms the different sum and bytecount being downloaded. I have attached the file if you want to inspect.

```bash
> curl -LO https://apt.releases.commonfate.io/dists/stable/main/binary-amd64/Packages.gz
> ls -l --size=bytes Packages.gz 
.rw-rw-r-- jacob jacob 1488  Fri Oct 11 08:48:41 2024 -- Packages.gz
> sha256sum Packages.gz 
38ce6870439f0b6de9caffce2f3e39e5ed9f612e9e1473f5d261520ffa4847aa  Packages.gz
> sha1sum Packages.gz 
69e766a87304d39aaabfd56805ead02f35d42f68  Packages.gz
> md5sum Packages.gz 
9a4df2b473e0a7d1b8626a0739407351  Packages.gz
```

[Packages.gz](https://github.com/user-attachments/files/17344250/Packages.gz)

**Comment by jgreenbow** [comment] 2024-10-11 15:10
I should also note that other files fail the checksum

```bash
> x=Packages
> curl -LO https://apt.releases.commonfate.io/dists/stable/main/binary-amd64/$x
> wc -c $x && sha256sum $x && sha1sum $x && md5sum $x
6750 Packages
6d156558ba75b480f182f1e04205235860f7f97162cf0d89a9dd138cbea286e3  Packages
02b7a3a24693df03297bf3311c364a199d00faf9  Packages
e9f7a9fe0065caa9ccc84cf9d19f7a17  Packages
```

The Oct 4 InRelease shows `SHA256: 5f4b4c088b592ee8c546e1eeb03b485ac924ad2f0fece053b9e74f027269f05f 6300 main/binary-amd64/Packages`

**Comment by jgreenbow** [comment] 2024-10-11 15:12
What is the InRelease file supposed to be out of curosity?

**Comment by chrismacnaughton-lambda** [comment] 2024-10-11 17:49
I'm also seeing this, trying to install `granted` on a new laptop today

```
E: Failed to fetch https://apt.releases.commonfate.io/dists/stable/main/binary-amd64/Packages.gz  File has unexpected size (1488 != 1412). Mirror sync in progress? [IP: 2600:9000:2511:c200:3:ea7b:c8c0:93a1 443]
   Hashes of expected file:
    - Filesize:1412 [weak]
    - SHA256:758a8d554a5630dd2f890146b57d3fb9eda02dd08229b31fb6594a5cca0fb6cc
    - SHA1:9ccfdd57482a6be010a8b8d4eb7b38fca364b368 [weak]
    - MD5Sum:a95185e90cbae66eeb729301a5dda9d9 [weak]
   Release file created at: Fri, 04 Oct 2024 11:38:17 +0000
  ```

**Comment by chrnorm** [comment] 2024-10-13 23:10
@jgreenbow @chrismacnaughton-lambda sorry for the inconvenience here, I thought I'd solved it in my initial comment on this issue.

I've just triggered an entirely new APT release which has refreshed the InRelease file, I've confirmed that I've been able to update to our latest release v0.35.1 on an Ubuntu 22.04.5 box with `amd64` architecture.

Could you please confirm if it's now working for you, and if it isn't, let me know what architecture and Ubuntu version you're running?

**Comment by chrnorm** [comment] 2024-10-14 14:55
@rotten thanks - I will close this now as fixed. @jgreenbow @chrismacnaughton-lambda please comment if still not working for you and I will re-open.

**Closed by chrnorm** 2024-10-14 14:55 UTC

**Comment by chrismacnaughton-lambda** [comment] 2024-10-15 12:44
Worked for me too @chrnorm!

**Comment by jgreenbow** [comment] 2024-10-15 16:34
@chrnorm Worked for me, thanks!

**Comment by subodhchhabra** [comment] 2024-10-21 16:38
@chrnorm -- this is happening again now for ubuntu-20.04
`Err:20 https://apt.releases.commonfate.io stable/main amd64 Packages
  File has unexpected size (1569 != 1490). Mirror sync in progress? [IP: 13.32.208.7 443]
  Hashes of expected file:
   - Filesize:1490 [weak]
   - SHA256:cdeef3cdf64905f3f1a0fe6b5db831273177070293d9e928bbeb7955a51f413c
   - SHA1:eeed1ee278e5e7315f80a4072f99d46b303d5087 [weak]
   - MD5Sum:9c14e4ba1d4b1bc2bc103b3d08d0126c [weak]
  Release file created at: Sun, 13 Oct 2024 23:03:40 +0000
Fetched 1,945 B in 2s (1,273 B/s)
Reading package lists... Done
E: Failed to fetch https://apt.releases.commonfate.io/dists/stable/main/binary-amd64/Packages.gz  File has unexpected size (1569 != 1490). Mirror sync in progress? [IP: 13.32.208.7 443]
   Hashes of expected file:
    - Filesize:1490 [weak]
    - SHA256:cdeef3cdf64905f3f1a0fe6b5db831273177070293d9e928bbeb7955a51f413c
    - SHA1:eeed1ee278e5e7315f80a4072f99d46b303d5087 [weak]
    - MD5Sum:9c14e4ba1d4b1bc2bc103b3d08d0126c [weak]
   Release file created at: Sun, 13 Oct 2024 23:03:40 +0000
`
